NAME = zadanie2_4
NAME2 = zadanie1
NAME3 = zadanie3asmDoC
NAME4 = zadanie3CDoAsm
FUNKCJA = get_counter
FUNKCJA2 = get_counter2

$(NAME): $(NAME).c
	gcc -m32 -Wall -O3 -std=c99 $(NAME).c $(FUNKCJA).s $(FUNKCJA2).s -o $(NAME) -g

# $(NAME2): $(NAME2).s
# 	gcc -m32 -Wall -O3 -std=c99 $(NAME2).s -o $(NAME2) -g

# $(NAME3): $(NAME3).c
# 	gcc -m32 -Wall -O3 -std=c99 $(NAME3).c $(NAME3).s -o $(NAME3) -g

#$(NAME4): $(NAME4).c
#	gcc -m32 -Wall -O3 -std=c99 $(NAME4).c $(NAME4).s -o $(NAME4) -g
