NAME = zadanie1-4
NAME2 = zadanie5

# #
# $(NAME): $(NAME).c
# 	gcc -m32 -Wall -O3 -std=c99 $(NAME).c *.s -o $(NAME) -g

$(NAME2): $(NAME2).c
	gcc -m32 -Wall -O3 -std=c99 $(NAME2).c *.s -o $(NAME2) -g
